
spring:
  data.mongodb:
    uri: mongodb+srv://twitch:001200@twichmongo.owqiu.mongodb.net/spring?authSource=admin&replicaSet=atlas-wl7gr9-shard-0&readPreference=primary&appname=MongoDB%20Compass&ssl=true

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
